---
- yum: name=httpd state=latest

- service: name=httpd state=started enabled=yes

- template:
    src: vhosts.conf.j2
    dest: "/etc/httpd/conf.d/{{ ansible_hostname }}.conf"
    force: yes
    owner: root
    group: root
    mode: 0644
  notify:
    - restart httpd
- copy:
    src: html/
    dest: /var/www/html
